### ISSUE TITLE
==> becomes \<Longigtarrow>rh

### ISSUE THREAD

**Issue by gh-salt** [m-fleury/isabelle-emacs#48]
This also affects => (just the h is moved out in that case) and it seems related to #6 but also affects emacs 27.

**Comment by gh-salt** [comment]
workaround: disable evil-escape-mode

**Comment by m-fleury** [comment]
For reasons that have yet to be determined this is caused by using both the coq and the isabelle layer in spacemacs*. So a slightly better workaround is removing the coq layer.


* From a very quick look at the issue yesterday: a quail function is redefined to support evil-escape-mode. The redefinition is probably lost in that case.

**Comment by m-fleury** [comment]
in the 2022-RC4 symbols are handled slightly differently. The goal is now composed of symbols instead of unicode, so no replacement is needed anymore.
